<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-M1AAM1H" failures="1" tests="5" name="com.yourlogo.test.Test_Login" time="80.331" errors="0" timestamp="2020-08-24T09:42:38 IST" skipped="0">
  <testcase classname="com.yourlogo.test.Test_Login" name="emailIdBlank" time="19.740"/>
  <system-out>
[INFO] : Setting up Test Data for Login module [INFO] : Application Started [INFO] : Enter login details and click on SignIn  </system-out>
  <testcase classname="com.yourlogo.test.Test_Login" name="passwordBlank" time="15.195"/>
  <system-out>
[INFO] : Setting up Test Data for Login module [INFO] : Application Started [INFO] : Enter login details and click on SignIn  </system-out>
  <testcase classname="com.yourlogo.test.Test_Login" name="invalidEmailId" time="15.156"/>
  <system-out>
[INFO] : Setting up Test Data for Login module [INFO] : Application Started [INFO] : Enter login details and click on SignIn  </system-out>
  <testcase classname="com.yourlogo.test.Test_Login" name="invalidPassword" time="14.885"/>
  <system-out>
[INFO] : Setting up Test Data for Login module [INFO] : Application Started [INFO] : Enter login details and click on SignIn  </system-out>
  <testcase classname="com.yourlogo.test.Test_Login" name="validLogin" time="15.355">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.yourlogo.test.Test_Login.validLogin(Test_Login.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validLogin -->
  <system-out>
[INFO] : Setting up Test Data for Login module [INFO] : Application Started [INFO] : Enter login details and click on SignIn  </system-out>
</testsuite> <!-- com.yourlogo.test.Test_Login -->
